### ISSUE TITLE
undefined method `configure' for RSpec:Module

### ISSUE THREAD

**Issue by atd** [Hirurg103/capybara_select2#2]
Hi @Hirurg103 

I upgraded to version `0.2.1` but when I run the specs I get:

```
/usr/local/rvm/gems/ruby-2.5.1@ideas4all-brasaas/gems/bundler-1.16.3/lib/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There wa
s an error while trying to load the gem 'capybara-select-2'.                                                                                      
Gem Load Error is: undefined method `configure' for RSpec:Module                                                                                  
Backtrace for gem load error is:                                                                                                                  
/usr/local/rvm/gems/ruby-2.5.1@ideas4all-brasaas/gems/capybara-select-2-0.2.1/lib/capybara_select2.rb:10:in `<top (required)>'                    
/usr/local/rvm/gems/ruby-2.5.1@ideas4all-brasaas/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'                     
/usr/local/rvm/gems/ruby-2.5.1@ideas4all-brasaas/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'            
/usr/local/rvm/gems/ruby-2.5.1@ideas4all-brasaas/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'             
/usr/local/rvm/gems/ruby-2.5.1@ideas4all-brasaas/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'                     
/usr/local/rvm/gems/ruby-2.5.1@ideas4all-brasaas/gems/capybara-select-2-0.2.1/lib/capybara-select-2.rb:1:in `<top (required)>'     
....
```

Maybe some `require` is needed to use `Rspec.configure`?

**Comment by Hirurg103** [comment]
Hi @atd

published a new version with the bug fix. Could you try to upgrade and see if an error if resolved

**Comment by Hirurg103** [comment]
Hello @atd 

I updated the gem so it will detects select2 version automatically. You might try it out if you want

**Comment by atd** [comment]
Perfect! It works like a charm for me :clap: :clap:
